# Generated by Django 3.2.1 on 2021-05-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_review_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
    ]
